Revert "target-alpha: Add vector implementation for CMPBGE"
This reverts commit 20dae7877636de47b800314caf12a4a65240c8e7.

Unfortunately the SSE2 code here fails to compile on some versions
of gcc:
 target-alpha/int_helper.c:77:24: error: invalid operands to binary >=
 (have '__vector(16) unsigned char' and '__vector(16) unsigned char')

Signed-off-by: Peter Maydell <peter.maydell@linaro.org>