hw/mips: Add dependency MIPS_CPS -> MIPS_ITU
The Inter-Thread Communication Unit (ITU, introduced in commit
f814e2f8555) is part of the Coherent Processing System (CPS),
as describe in commit d8d686ebf63:

    Make ITU available in the system if CPU supports multithreading
    and is part of CPS.

Have CPS select ITU in Kconfig to avoid the following build failure:

  /usr/bin/ld: libqemu-mips64el-softmmu.fa.p/hw_mips_cps.c.o: in function `mips_cps_realize':
  hw/mips/cps.c:104: undefined reference to `mips_itu_get_tag_region'

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20190311005618.19007-5-philmd@redhat.com>