error: De-duplicate code creating Error objects
Duplicated when commit 9e35b97 added error_set_errno(), and again when
commit 3b19b63 added error_set_win32().

Make the original copy in error_set() reusable by factoring out
error_setv(), then rewrite error_set_errno() and error_set_win32() on
top of it.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Reviewed-by: Eric Blake <eblake@redhat.com>